---
title: "Posterior Inference"
author: "Authors: Se Yoon Lee and Bani Mallick"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Objective of Rmd file is to provide posterior analysis for the production results from the shale oil wells in the Eagle Ford Shale of South Texas


### Load Spatial Weibull Model (SWM)
```{r}
  setwd("C:/Users/seyoonlee/OneDrive/Documents/GitHub/SWM/R codes")
  source("SWM.R")
```

### Load Dataset
```{r}
  setwd("C:/Users/seyoonlee/OneDrive/Documents/GitHub/SWM/Dataset/")
  load("Production_Results_Eagle_Ford.RData")
  
  # Set number of testing wells
  N.test = 36
  N = 360 - N.test # number of training wells   
  
  
  Y = log(Production_Results_Eagle_Ford$P[1:N,])
  X = scale(Production_Results_Eagle_Ford$X, center = TRUE, scale = TRUE)[1:N,]
  Loc = Production_Results_Eagle_Ford$Loc[1:N,]
  
  te.Y = log(Production_Results_Eagle_Ford$P[-c(1:N),])
  te.X = scale(Production_Results_Eagle_Ford$X, center = TRUE, scale = TRUE)[-c(1:N),]
  te.Loc = Production_Results_Eagle_Ford$Loc[-c(1:N),]
```

### Locations of training and testing wells
```{r}
par(mfrow = c(1,1))
# install.packages("maps") ; 
library("maps") ; Sys.getenv("R_LIBS_USER")
map('state', 'texas',fill = TRUE,col = "grey",
    xlim = c(-100.5,-96),exact = TRUE,
    ylim = c(28,30))
title("Locations of training wells (black dots) and testing wells (red triangles).")
points( x = Loc[,2], y = Loc[,1],  col = "black", pch = 20)
points( x = te.Loc[,2], y = te.Loc[,1],  col = "red", pch = 17)
```



### Training the Spatial Weibul Model with Gibbs sampler
```{r include=FALSE}
Post.Inf.Res = SWM(Y = Y, X = X, Loc = Loc,
                     burn=10,nmc=10,thin=1)
```

Post.Inf.Res$thinned.beta.1[1,]
